### ISSUE TITLE
thank you for your effort

### ISSUE THREAD

**Issue by Stephenzero** [subham8907/Linkumori#1]
thank you for your effort,
I wish I could do some work for you, but unfortunately, I am not a coder, actually I did not know too much about coding.
but thank you anyway
if you got any thing to get intouch with me. leave me a message

**Comment by subham8907** [comment]
Thank you so much for your wonderful message - it really made my day! Your appreciation means a lot to me. The best way to support this project would be to share it with others who might find it helpful. Every share helps the project reach more people who could benefit from it. Thank you again for your kind words and support! 😊

**Comment by macOS-Mavericks** [comment]
Any chance you can make this for Firefox (LibreWolf) too please?

Hoping to find something that can tackle the Slickdeals site.

**Comment by subham8907** [comment]
yeah it is possible to make firefox version but it take time because firefox implementation of DNR is not that great so maybe in december you will get first beta for firefox and  firefox fork like librewolf or floorp
