### ISSUE TITLE
GitHub Action log not working

### ISSUE THREAD

**Issue by PikachuEXE** [subham8907/Linkumori#11]
Already added github.com to whitelist
![image](https://github.com/user-attachments/assets/3bf70540-2585-4ed7-8354-959f1ed9d62c)
![image](https://github.com/user-attachments/assets/fd20700b-67b6-4b6e-96c6-f5fd7401b33c)

![image](https://github.com/user-attachments/assets/f70948d6-3874-4b2c-84ee-b19bc5443291)

**Comment by subham8907** [comment]
Whitelist feature is not fully ready i know that issue need some more fixes thank you for reporting this

**Comment by subham8907** [comment]
https://github.com/subham8907/Linkumori/releases/tag/B27.0

**Comment by subham8907** [comment]
Try B27.0 will work

**Comment by PikachuEXE** [comment]
Confirmed working

**Comment by subham8907** [comment]
hello can i have a favour can you share my project to other people it will be great for future of this project if many people join or use this project

**Comment by PikachuEXE** [comment]
Just did - https://liker.social/@PikachuEXE/113478711249414666
