### ISSUE TITLE
Feature request: prefill whitelist domain name with current tab's domain or add button to add current tab domain to whitelist

### ISSUE THREAD

**Issue by PikachuEXE** [subham8907/Linkumori#16]
Something like
![2024-11-14 09_27_45-](https://github.com/user-attachments/assets/f57db88a-a323-44c6-b8cd-98c36047fbcf)

**Comment by subham8907** [comment]
Will look this issue

**Comment by subham8907** [comment]
https://github.com/subham8907/Linkumori/releases/tag/B28

**Comment by subham8907** [comment]
Your issue fixed
read patch notes

**Comment by PikachuEXE** [comment]
Ya
Not prefill but works better
Though what's `Added clear visual indicators for whitelist status`? Menu item changed to `Remove`?

**Comment by subham8907** [comment]
we due to being lazy commit message is not written by me but my idiot friend 
Aside from this i implemented simillar implementation you wanted

**Comment by PikachuEXE** [comment]
Might be good (for UX but not urgent) to show site is whitelisted on context menu (instead of just big icon) or even extension icon (so no need to click)

Another issue though

**Comment by subham8907** [comment]
![Screenshot 2024-11-14 201648](https://github.com/user-attachments/assets/a8e5ddac-ee14-40df-b55f-1fdbd7a66064)
how this looks

**Comment by subham8907** [comment]
![Screenshot 2024-11-14 203437](https://github.com/user-attachments/assets/271fd6ab-3039-4314-bb06-7e8b98eaf30d)
how this looks

**Comment by subham8907** [comment]
https://github.com/subham8907/Linkumori/releases/tag/B29

**Comment by PikachuEXE** [comment]
Better to show a message below the buttons (or somewhere above the list
If I have a long list I won't see the domain being added
The message for domain already added or cannot get domain name can also be displayed at the same place

**Comment by subham8907** [comment]
Also please install B35 because now starting from B35 extension will be autoupdate

**Comment by PikachuEXE** [comment]
I did (though in extensions page it shows a different value

**Comment by subham8907** [comment]
It will fixed in next update

**Comment by PikachuEXE** [comment]
Great updates (B43
But it seems the whitelist tab is not in sync
![2024-11-16 07_13_16-Feature request_ prefill whitelist domain name with current tab's domain or add ](https://github.com/user-attachments/assets/91e2d39a-30c0-4254-b2a4-962988bba1f4)

**Comment by subham8907** [comment]
Meaning what exactly the issue is

**Comment by subham8907** [comment]
I mean what sync issue we are talking about

**Comment by PikachuEXE** [comment]
I forgot to add this
![2024-11-16 12_55_42-Feature request_ prefill whitelist domain name with current tab's domain or add ](https://github.com/user-attachments/assets/9fc87b30-2313-4d47-a043-7b66300953be)

Copied from above
![2024-11-16 07_13_16-Feature request_ prefill whitelist domain name with current tab's domain or add ](https://github.com/user-attachments/assets/91e2d39a-30c0-4254-b2a4-962988bba1f4)

**Comment by subham8907** [comment]
Well this is a feature not bug i think intentionally made it that way

**Comment by subham8907** [comment]
I Will fix that latter

**Comment by subham8907** [comment]
issue is fixed in B45

**Comment by subham8907** [comment]
https://github.com/subham8907/web.linkumori/tree/main hello can you host download page in your server online i cannot this website in github page so can you help me setup this webpage for free
i provide source of code webpage please check and help me
to run you run node server.js
