### ISSUE TITLE
Support installing via crx file

### ISSUE THREAD

**Issue by PikachuEXE** [subham8907/Linkumori#3]
I found 2 actions
https://github.com/marketplace/actions/pack-chromium-extension
https://github.com/marketplace/actions/sign-chrome-extension-crx-file

**Comment by subham8907** [comment]
Your request is fulfilled check new release you will get crx file along with source code

**Comment by PikachuEXE** [comment]
Oh yea

**Comment by subham8907** [comment]
Can you make pull request for proposed changes in readme
